#!/usr/bin/env python3
"""
Improved Visualization Script for Mesh Normalization Statistics

This script reads the CSV data generated by the normalization script and creates
enhanced, publication-quality plots with better formatting, larger text, and
improved visual clarity.

Features:
- Larger, clearer text and labels
- Better color schemes and styling
- Statistical annotations (mean, std, median)
- Improved histogram binning and outlier handling
- Professional formatting for reports/presentations
- Multiple plot styles (histograms, box plots, violin plots)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import matplotlib.patches as mpatches
import argparse

# Set style and parameters for better plots
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")

# Configure matplotlib for larger, clearer text
plt.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 16,
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'legend.fontsize': 12,
    'figure.titlesize': 18,
    'axes.linewidth': 1.5,
    'grid.linewidth': 0.8,
    'lines.linewidth': 2,
    'patch.linewidth': 1.5
})

# Configuration
BASE = Path(__file__).parent.parent.resolve()
DATA_DIR = BASE / "Preprocessing/figures"
OUTPUT_DIR = BASE / "Preprocessing/figures/improved_plots"

def load_and_clean_data(csv_path):
    """Load CSV data and clean it for analysis."""
    df = pd.read_csv(csv_path)
    # Remove any rows with all NaN values
    df = df.dropna(how='all')
    # Fill NaN values with appropriate defaults or remove them
    df = df.dropna()
    return df

def add_stats_text(ax, data, x_pos=0.02, y_pos=0.98):
    """Add statistical information text box to a plot."""
    mean_val = np.mean(data)
    std_val = np.std(data)
    median_val = np.median(data)
    min_val = np.min(data)
    max_val = np.max(data)
    
    stats_text = f'Mean: {mean_val:.4f}\n'
    stats_text += f'Std: {std_val:.4f}\n'
    stats_text += f'Median: {median_val:.4f}\n'
    stats_text += f'Min: {min_val:.4f}\n'
    stats_text += f'Max: {max_val:.4f}\n'
    stats_text += f'N: {len(data)}'
    
    # Create text box
    textstr = stats_text
    props = dict(boxstyle='round', facecolor='wheat', alpha=0.8)
    ax.text(x_pos, y_pos, textstr, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)

def create_enhanced_histogram(data, title, xlabel, ylabel, filename, 
                            color='skyblue', bins=50, show_outliers=True, show_plot=True):
    """Create an enhanced histogram with better styling and statistics."""
    
    fig, ax = plt.subplots(figsize=(12, 8))
    
    # Calculate statistics for outlier detection
    q1, q3 = np.percentile(data, [25, 75])
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    
    # Separate inliers and outliers
    inliers = data[(data >= lower_bound) & (data <= upper_bound)]
    outliers = data[(data < lower_bound) | (data > upper_bound)]
    
    # Create histogram for inliers
    n, bins, patches = ax.hist(inliers, bins=bins, alpha=0.7, color=color, 
                              edgecolor='black', linewidth=0.5, label='Data')
    
    # Add outlier information if present
    if len(outliers) > 0 and show_outliers:
        # Add outlier bar
        outlier_bin_width = (bins[1] - bins[0])
        outlier_x = bins[-1] + outlier_bin_width * 0.5
        ax.bar(outlier_x, len(outliers), width=outlier_bin_width, 
               alpha=0.7, color='red', edgecolor='black', linewidth=0.5,
               label=f'Outliers (n={len(outliers)})')
        
        # Extend x-axis to show outlier bar
        ax.set_xlim(bins[0], outlier_x + outlier_bin_width)
    
    # Add vertical lines for mean and median
    mean_val = np.mean(data)
    median_val = np.median(data)
    ax.axvline(mean_val, color='red', linestyle='--', linewidth=2, 
               label=f'Mean: {mean_val:.4f}')
    ax.axvline(median_val, color='green', linestyle='--', linewidth=2, 
               label=f'Median: {median_val:.4f}')
    
    # Styling
    ax.set_title(title, fontweight='bold', pad=20)
    ax.set_xlabel(xlabel, fontweight='bold')
    ax.set_ylabel(ylabel, fontweight='bold')
    ax.legend(loc='upper right', framealpha=0.9)
    ax.grid(True, alpha=0.3)
    
    # Add statistics text box
    add_stats_text(ax, data)
    
    # Tight layout and save
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight', facecolor='white')
    
    if show_plot:
        plt.show()
    else:
        plt.close()

def create_comparison_plot(before_data, after_data, title, xlabel, filename, show_plot=True):
    """Create a side-by-side comparison plot."""
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
    
    # Before plot
    ax1.hist(before_data, bins=50, alpha=0.7, color='lightcoral', 
             edgecolor='black', linewidth=0.5)
    ax1.axvline(np.mean(before_data), color='red', linestyle='--', linewidth=2, 
                label=f'Mean: {np.mean(before_data):.4f}')
    ax1.set_title('Before Processing', fontweight='bold')
    ax1.set_xlabel(xlabel, fontweight='bold')
    ax1.set_ylabel('Count', fontweight='bold')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    add_stats_text(ax1, before_data)
    
    # After plot
    ax2.hist(after_data, bins=50, alpha=0.7, color='lightgreen', 
             edgecolor='black', linewidth=0.5)
    ax2.axvline(np.mean(after_data), color='green', linestyle='--', linewidth=2, 
                label=f'Mean: {np.mean(after_data):.4f}')
    ax2.set_title('After Processing', fontweight='bold')
    ax2.set_xlabel(xlabel, fontweight='bold')
    ax2.set_ylabel('Count', fontweight='bold')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    add_stats_text(ax2, after_data)
    
    # Main title
    fig.suptitle(title, fontsize=20, fontweight='bold', y=0.98)
    
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight', facecolor='white')
    
    if show_plot:
        plt.show()
    else:
        plt.close()

def create_box_violin_plot(data_dict, title, ylabel, filename, show_plot=True):
    """Create combined box and violin plots for multiple datasets."""
    
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 12))
    
    # Prepare data for plotting
    plot_data = []
    labels = []
    for key, values in data_dict.items():
        if len(values) > 0:
            plot_data.append(values)
            labels.append(key.replace('_', ' ').title())
    
    # Box plot
    bp = ax1.boxplot(plot_data, labels=labels, patch_artist=True, 
                     notch=True, showfliers=True)
    
    # Color the box plots
    colors = ['lightcoral', 'lightgreen', 'lightblue', 'lightyellow']
    for patch, color in zip(bp['boxes'], colors[:len(bp['boxes'])]):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)
    
    ax1.set_title('Box Plot Comparison', fontweight='bold', fontsize=16)
    ax1.set_ylabel(ylabel, fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.tick_params(axis='x', rotation=45)
    
    # Violin plot
    parts = ax2.violinplot(plot_data, positions=range(1, len(plot_data) + 1), 
                          showmeans=True, showmedians=True)
    
    # Color the violin plots
    for i, pc in enumerate(parts['bodies']):
        pc.set_facecolor(colors[i % len(colors)])
        pc.set_alpha(0.7)
    
    ax2.set_title('Violin Plot Comparison', fontweight='bold', fontsize=16)
    ax2.set_ylabel(ylabel, fontweight='bold')
    ax2.set_xticks(range(1, len(labels) + 1))
    ax2.set_xticklabels(labels, rotation=45)
    ax2.grid(True, alpha=0.3)
    
    # Main title
    fig.suptitle(title, fontsize=20, fontweight='bold', y=0.95)
    
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight', facecolor='white')
    
    if show_plot:
        plt.show()
    else:
        plt.close()

def create_summary_dashboard(df, filename, show_plot=True):
    """Create a comprehensive dashboard with all metrics."""
    
    fig = plt.figure(figsize=(20, 16))
    
    # Create a 3x2 subplot grid
    gs = fig.add_gridspec(3, 2, hspace=0.3, wspace=0.3)
    
    # Barycenter before vs after
    ax1 = fig.add_subplot(gs[0, :])
    x = np.arange(len(df))
    ax1.scatter(x, df['bary_before_translation'], alpha=0.6, color='red', 
                s=20, label='Before Translation')
    ax1.scatter(x, df['bary_after_translation'], alpha=0.6, color='green', 
                s=20, label='After Translation')
    ax1.set_title('Barycenter Offset: Before vs After Translation', 
                  fontweight='bold', fontsize=16)
    ax1.set_xlabel('Mesh Index', fontweight='bold')
    ax1.set_ylabel('Distance to Origin', fontweight='bold')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # Bounding box before scaling histogram
    ax2 = fig.add_subplot(gs[1, 0])
    ax2.hist(df['bbox_before_scaling'], bins=50, alpha=0.7, color='skyblue', 
             edgecolor='black', linewidth=0.5)
    ax2.set_title('Bounding Box Before Scaling', fontweight='bold')
    ax2.set_xlabel('Length', fontweight='bold')
    ax2.set_ylabel('Count', fontweight='bold')
    ax2.grid(True, alpha=0.3)
    
    # Bounding box after scaling histogram
    ax3 = fig.add_subplot(gs[1, 1])
    ax3.hist(df['bbox_after_scaling'], bins=50, alpha=0.7, color='orange', 
             edgecolor='black', linewidth=0.5)
    ax3.set_title('Bounding Box After Scaling', fontweight='bold')
    ax3.set_xlabel('Length', fontweight='bold')
    ax3.set_ylabel('Count', fontweight='bold')
    ax3.grid(True, alpha=0.3)
    
    # Statistics summary table
    ax4 = fig.add_subplot(gs[2, :])
    ax4.axis('tight')
    ax4.axis('off')
    
    # Create statistics table
    stats_data = []
    for col in ['bary_before_translation', 'bary_after_translation', 
                'bbox_before_scaling', 'bbox_after_scaling']:
        if col in df.columns:
            data = df[col].dropna()
            stats_data.append([
                col.replace('_', ' ').title(),
                f'{np.mean(data):.6f}',
                f'{np.std(data):.6f}',
                f'{np.median(data):.6f}',
                f'{np.min(data):.6f}',
                f'{np.max(data):.6f}',
                f'{len(data)}'
            ])
    
    table = ax4.table(cellText=stats_data,
                     colLabels=['Metric', 'Mean', 'Std Dev', 'Median', 'Min', 'Max', 'Count'],
                     cellLoc='center',
                     loc='center',
                     bbox=[0, 0, 1, 1])
    
    table.auto_set_font_size(False)
    table.set_fontsize(12)
    table.scale(1, 2)
    
    # Style the table
    for i in range(len(stats_data) + 1):
        for j in range(7):
            cell = table[(i, j)]
            if i == 0:  # Header row
                cell.set_facecolor('#4CAF50')
                cell.set_text_props(weight='bold', color='white')
            else:
                cell.set_facecolor('#f0f0f0' if i % 2 == 0 else 'white')
    
    ax4.set_title('Statistical Summary', fontweight='bold', fontsize=16, pad=20)
    
    # Main title
    fig.suptitle('Mesh Normalization Analysis Dashboard', 
                 fontsize=24, fontweight='bold', y=0.95)
    
    plt.savefig(filename, dpi=300, bbox_inches='tight', facecolor='white')
    
    if show_plot:
        plt.show()
    else:
        plt.close()

def main(show_plots=True):
    """Main function to create all improved visualizations.
    
    Parameters:
    -----------
    show_plots : bool, default True
        Whether to display plots interactively in addition to saving them
    """
    
    # Create output directory
    OUTPUT_DIR.mkdir(exist_ok=True, parents=True)
    
    # Load data
    csv_path = DATA_DIR / "normalization_statistics.csv"
    if not csv_path.exists():
        print(f"Error: CSV file not found at {csv_path}")
        print("Please run the normalization script first to generate the data.")
        return
    
    print(f"Loading data from {csv_path}")
    df = load_and_clean_data(csv_path)
    print(f"Loaded {len(df)} data points")
    
    if show_plots:
        print("\nDisplaying plots interactively (close each plot window to continue)...")
    
    # Create individual enhanced histograms
    print("Creating enhanced histogram plots...")
    
    # Barycenter before translation
    create_enhanced_histogram(
        df['bary_before_translation'], 
        'Barycenter Offset Before Translation',
        'Distance to Origin', 
        'Frequency',
        OUTPUT_DIR / 'enhanced_barycenter_before.png',
        color='lightcoral',
        show_plot=show_plots
    )
    
    # Barycenter after translation
    create_enhanced_histogram(
        df['bary_after_translation'], 
        'Barycenter Offset After Translation',
        'Distance to Origin', 
        'Frequency',
        OUTPUT_DIR / 'enhanced_barycenter_after.png',
        color='lightgreen',
        show_plot=show_plots
    )
    
    # Bounding box before scaling
    create_enhanced_histogram(
        df['bbox_before_scaling'], 
        'Bounding Box Longest Side Before Scaling',
        'Length', 
        'Frequency',
        OUTPUT_DIR / 'enhanced_bbox_before.png',
        color='skyblue',
        show_plot=show_plots
    )
    
    # Bounding box after scaling
    create_enhanced_histogram(
        df['bbox_after_scaling'], 
        'Bounding Box Longest Side After Scaling',
        'Length', 
        'Frequency',
        OUTPUT_DIR / 'enhanced_bbox_after.png',
        color='orange',
        show_outliers=False,  # After scaling should be normalized
        show_plot=show_plots
    )
    
    # Create comparison plots
    print("Creating comparison plots...")
    
    create_comparison_plot(
        df['bary_before_translation'], 
        df['bary_after_translation'],
        'Barycenter Offset: Before vs After Translation',
        'Distance to Origin',
        OUTPUT_DIR / 'barycenter_comparison.png',
        show_plot=show_plots
    )
    
    create_comparison_plot(
        df['bbox_before_scaling'], 
        df['bbox_after_scaling'],
        'Bounding Box Size: Before vs After Scaling',
        'Length',
        OUTPUT_DIR / 'bbox_comparison.png',
        show_plot=show_plots
    )
    
    # Create box and violin plots
    print("Creating box and violin plots...")
    
    data_dict = {
        'bary_before_translation': df['bary_before_translation'].values,
        'bary_after_translation': df['bary_after_translation'].values,
        'bbox_before_scaling': df['bbox_before_scaling'].values,
        'bbox_after_scaling': df['bbox_after_scaling'].values
    }
    
    create_box_violin_plot(
        data_dict,
        'Statistical Distribution Comparison of All Metrics',
        'Value',
        OUTPUT_DIR / 'statistical_comparison.png',
        show_plot=show_plots
    )
    
    # Create comprehensive dashboard
    print("Creating summary dashboard...")
    create_summary_dashboard(df, OUTPUT_DIR / 'normalization_dashboard.png', show_plot=show_plots)
    
    print(f"\nAll improved visualizations saved to: {OUTPUT_DIR}")
    print("\nGenerated files:")
    for file in OUTPUT_DIR.glob("*.png"):
        print(f"  - {file.name}")
    
    if show_plots:
        print("\nAll plots have been displayed and saved!")
    else:
        print("\nAll plots have been saved (display was disabled).")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Create improved visualizations from normalization statistics')
    parser.add_argument('--no-show', action='store_true', 
                       help='Save plots without displaying them (useful for batch processing)')
    
    args = parser.parse_args()
    show_plots = not args.no_show
    
    main(show_plots=show_plots)