#!/usr/bin/env python3
"""
Simple test to verify the updated analysis cache path mappings
"""

import os
import sys
sys.path.append('.')

def test_analysis_cache_paths():
    """Test the updated path mappings in analysis_cache.py"""
    print("🧪 TESTING UPDATED ANALYSIS CACHE PATH MAPPINGS")
    print("=" * 55)
    
    # Simulate the path mapping logic from analysis_cache.py
    path_mapping = {
        # Original datasets - analysis files saved in Preprocessing folder
        'Data': [
            'Preprocessing/analysis_results_data.csv',
            'Preprocessing/analysis_results.csv',
            'Datasets/Data/analysis_results.csv'
        ],
        'Data_sampled': [
            'Preprocessing/analysis_results_data_sampled.csv',
            'Preprocessing/analysis_results_sampled.csv',
            'Datasets/Data_sampled/analysis_results.csv'
        ],
        # Processed datasets - analysis files saved in dataset folder
        'UnifiedPreprocessed/Data': [
            'Datasets/UnifiedPreprocessed/Data/analysis_results.csv',
            'Datasets/UnifiedPreprocessed/analysis_results.csv',
            'Preprocessing/analysis_results_resampled.csv'  # fallback
        ]
    }
    
    # Test base path discovery
    base_paths = [
        r"c:\Users\bar24\OneDrive - Universiteit Utrecht\Documents\School\UU Data Sceince MSc\2nd Year\Period 1\Multimedia Retrieval - INFOMR\Assignments\MultimediaRetrieval",
        r"c:\Users\bar24\OneDrive - Universiteit Utrecht\Documents\School\UU Data Sceince MSc\2nd Year\Period 1\Multimedia Retrieval - INFOMR\Assignments\MultimediaRetrieval\Src\obj-viewer-app"
    ]
    
    print("\n📂 CHECKING EXISTING ANALYSIS FILES:")
    print("-" * 40)
    
    for dataset, paths in path_mapping.items():
        print(f"\n🎯 Dataset: {dataset}")
        found_files = []
        
        for base_path in base_paths:
            for relative_path in paths:
                full_path = os.path.join(base_path, relative_path)
                if os.path.exists(full_path):
                    found_files.append(full_path)
                    print(f"  ✅ Found: {relative_path}")
                    break
            if found_files:
                break
        
        if not found_files:
            print(f"  ❌ No analysis file found for {dataset}")
            print(f"     Looked for: {paths}")
    
    print("\n📊 FILENAME MAPPING TEST:")
    print("-" * 30)
    
    # Test filename mapping scenarios
    test_cases = [
        {
            'displayed_filename': 'm1337_05_scaled.obj',
            'dataset': 'UnifiedPreprocessed/Data',
            'expected_analysis_filename': 'm1337_05_scaled.obj',  # if analysis generated by enhanced script
            'fallback_filename': 'm1337.obj'  # if using original dataset analysis
        },
        {
            'displayed_filename': 'm0001_05_scaled.obj',
            'dataset': 'UnifiedPreprocessed/Data',
            'expected_analysis_filename': 'm0001_05_scaled.obj',
            'fallback_filename': 'm0001.obj'
        }
    ]
    
    for case in test_cases:
        print(f"\n🔍 Test case: {case['displayed_filename']}")
        print(f"  Dataset: {case['dataset']}")
        print(f"  Expected in analysis CSV: {case['expected_analysis_filename']} OR {case['fallback_filename']}")
        
        # Simulate regex replacement from our enhanced merge logic
        import re
        fallback_filename = re.sub(r'_\d+_scaled\.obj$', '.obj', case['displayed_filename'])
        print(f"  Generated fallback: {fallback_filename}")
        print(f"  ✅ Fallback matches expected: {fallback_filename == case['fallback_filename']}")
    
    print("\n✅ Analysis cache path mapping test completed!")
    return True

if __name__ == "__main__":
    test_analysis_cache_paths()